# Generated by Django 5.1.6 on 2025-03-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("applied_date", models.DateField(blank=True, null=True)),
                ("interview_date", models.DateField(blank=True, null=True)),
                ("offer_date", models.DateField(blank=True, null=True)),
                (
                    "offer_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("decision_date", models.DateField(blank=True, null=True)),
                (
                    "decision_status",
                    models.CharField(
                        blank=True,
                        choices=[("Accepted", "Accepted"), ("Rejected", "Rejected")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("withdrawn_date", models.DateField(blank=True, null=True)),
                (
                    "withdrawal_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("custom_withdrawal_reason", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("date_applied", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("interview", "Interview Scheduled"),
                            ("offer", "Offer Received"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="applied",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
