# Generated by Django 5.1.6 on 2025-03-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="decision_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("applied", "Applied"),
                    ("interview", "Interview Scheduled"),
                    ("offer", "Offer Received"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("interview", "Interview Scheduled"),
                    ("offer", "Offer Received"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="applied",
                max_length=20,
            ),
        ),
    ]
