# Generated by Django 5.1.6 on 2025-03-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_alter_job_decision_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="decision_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Applied", "Applied"),
                    ("Interviewing", "Interview Scheduled"),
                    ("Offer", "Offer Received"),
                    ("Accepted", "Accepted"),
                    ("Rejected", "Rejected"),
                    ("Withdrawn", "Withdrawn"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
